# Site settings
title: Røde Mølle
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sjarmerende selskapslokale i Fredrikstad
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.rodemolle.no" # the base hostname & protocol for your site
twitter_username: treseksten

# Build settings
markdown: kramdown
